### ISSUE TITLE
Null source in version 3.0.1

### ISSUE THREAD

**Issue by Moosapoor** [sgjsakura/AspNetCore#39] opened 2019-10-23 09:29 UTC
Hi,
I have a problem when I upgraded my "Sakura.AspNetCore.Mvc.PagedList" package to version 3.0.1:

> **InvalidOperationException: The specified paging source came from the 'source' cannot be null**
> Sakura.AspNetCore.Mvc.TagHelpers.PagerTagHelper.GetPagingInfoFromSource(out int currentPage, out int totalPage)
> Sakura.AspNetCore.Mvc.TagHelpers.PagerTagHelper.GetPagingInfo(TagHelperContext context, out int currentPage, out int totalPage)
> Sakura.AspNetCore.Mvc.TagHelpers.PagerTagHelper.Process(TagHelperContext context, TagHelperOutput output)

I didn't have this problem in version 3.0.0 but in that version I had to add total-page and current-page to the tag helper manually as follow:
`<pager total-page="@Model.TotalPage" current-page="@Model.PageIndex" />`

Thanks,

**Comment by sgjsakura** [comment] 2019-10-24 04:28
Hi, thank you for your feedback, unfortunately I cannot reproduce your issue. Could you provide a minimum project for this problem? 

Best wishes,

**Comment by ian-cameron** [comment] 2019-10-25 22:45
[SakuraPagedList301.zip](https://github.com/sgjsakura/AspNetCore/files/3774070/SakuraPagedList301.zip)

 I'm not the original poster of this issue, but had the same problem.  Here is a minimum project with the problem.
Thanks!

**Comment by sgjsakura** [comment] 2019-10-28 05:09
Hi, this problem is fixed in the lastest version 3.0.2. I'm closing this issue and please feel free to reopen it if you meet any new problem.

**Closed by sgjsakura** 2019-10-28 05:09 UTC
