### ISSUE TITLE
[Documentation] Localization needed for taghelpers

### ISSUE THREAD

**Issue by peterpauldewit** [sgjsakura/AspNetCore#29] opened 2017-12-28 09:40 UTC
I guess it's been around since you fixed the language issue on the select taghelpers, but those wanting to use the select taghelpers without having localization anywhere else will have to add that in their startup file.

Since I don't consider that intuïtive I'm proposing to add it in the docs somewhere that you need to add the "services.AddLocalization();" in order for the taghelpers to work.

**Comment by sgjsakura** [comment] 2018-01-05 07:59
Hi, thank you for your feedback. This problem is caused by the dependency injection usage of services during the initialization the tag helpers. I will try to remove the strong dependency for optional services and this bug should be fixed in the next release.

**Comment by sgjsakura** [comment] 2018-05-31 10:04
Hi, this bug has been fixed in the tag helper library of version 1.3.7. I'm closing this issue and please feel free to reopen it if you have any new problem.

**Closed by sgjsakura** 2018-05-31 10:05 UTC
Labels: bug
