### ISSUE TITLE
asp-text-source tag helper does not use aspnetcore data annotation localization

### ISSUE THREAD

**Issue by alibghz** [sgjsakura/AspNetCore#26] opened 2017-05-10 06:39 UTC
When we set asp-text-source option for a asp-enum-for to for example "Name" it only show the exact name which we have in display method and cannot get the localized Name using built-in ASP.NET Core 1.1.* Data Annotation Localization.

![correctchoiseenum](https://cloud.githubusercontent.com/assets/6649054/25886033/02895468-3571-11e7-8be2-30822304a24e.PNG)

![correctchoiseresx](https://cloud.githubusercontent.com/assets/6649054/25886038/0acb68f0-3571-11e7-9c8b-8a028a5a2021.PNG)

![correctchoisesource](https://cloud.githubusercontent.com/assets/6649054/25886049/1a81c1d6-3571-11e7-9ea8-54bbc1fd3d0c.PNG)

![correctchoiseview](https://cloud.githubusercontent.com/assets/6649054/25886050/1db442d4-3571-11e7-8f66-29b8297baa62.PNG)

**Comment by sgjsakura** [comment] 2017-05-10 06:41
@alibghz Hi, this problem is confirmed and I'm working for a solution now. Please be patient for days.

Thank you for your feedback :-)

**Comment by sgjsakura** [comment] 2017-05-10 11:21
@alibghz Hi, please try to update the package to the lastest version 1.3.4 and see if the problem is solved.

Thank you again for your feedback and waiting for your kind reply :-)

**Comment by sgjsakura** [comment] 2017-05-18 08:07
Since the author of this issue does not reply for days, I'm closing it now. Please feel free to reopen it of submit new issues if you have new problem.

**Closed by sgjsakura** 2017-05-18 08:07 UTC
Labels: bug

**Comment by alibghz** [comment] 2017-05-22 17:14
Many thanks for your amazing support! I never thought that the issue could be solved in the same day of reporting and expected for several days waiting I just saw the notification and updated to new version and it worked, it is completely solved. Thanks again.
