### ISSUE TITLE
Sakura.AspNetCore.Mvc.PagedList tag helper is not recognised

### ISSUE THREAD

**Issue by erkan1991** [sgjsakura/AspNetCore#6] opened 2016-06-26 00:22 UTC
Hi, 

I have encountered an error when following the instructions for implementing pagination.
It seems like it doesn't like when i add `@addTagHelper *, Sakura.AspNetCore.Mvc.PagedList` to `_ViewImports.cs`

Fyi, I am using .net core RC2. If someone can please advise if i am doing something wrong or if there is a bug. 

Thank you

<img width="1388" alt="screen shot 2016-06-26 at 10 08 32 am" src="https://cloud.githubusercontent.com/assets/7500305/16359791/9fc29cac-3b86-11e6-8930-c3ba2bec0e71.png">

**Comment by sgjsakura** [comment] 2016-06-26 14:17
@erkan1991 HI, it seems you have not successfully installed the `Sakura.AspNetCore.Mvc.PagedList` package in your project. In order to find the exact reason for this error, could you please send a complete demo project to reproduce this problem? Thank you~

**Comment by sgjsakura** [comment] 2016-07-09 14:36
I'm closing this issue since the author has no reply. Please feel free to reopen it if you still have any question.

**Closed by sgjsakura** 2016-07-09 14:36 UTC
