### ISSUE TITLE
When in production, pager fails

### ISSUE THREAD

**Issue by mb2o** [sgjsakura/AspNetCore#21] opened 2017-03-08 12:57 UTC
When used in production on IIS and the path is something else than root, the paging functionality no longer works correctly. For example:

Suppose I have a site at **http://root/path/controller/action** and the next page should be **http://root/path/controller/action?page=2**. However, the link of the pager item will point to **http://root/controller/action?page=2**.

As you may have noticed, the **path** is missing from the link.
How would I configure the PagerItemOptions for this to work properly?

**Comment by sgjsakura** [comment] 2017-03-08 14:10
@mb2o Hi, thank you for your feedback. This problem may be caused by the URL calculation module inside the pager generator. I will take additional tests and fix it if there's any BUG.

**Comment by FiveAssedMonkey** [comment] 2017-03-11 20:45
I have the same problem, it seems as though it's not generating the relative path in the function.
What should be:
/VirtualDirectory/MyController?page=2
gets translated to just:
/MyController?page=2

**Comment by sgjsakura** [comment] 2017-03-12 06:38
@mb2o @FiveAssedMonkey Thank you for your feedback. This problem has been confirmed and fixed in the lastest version 2.0.12. I'm closing this issue and please feel free to reopen it if you have any further problem.

**Closed by sgjsakura** 2017-03-12 06:38 UTC
Labels: bug
