### ISSUE TITLE
Tag helpers seem to be broken on asp.net core 3

### ISSUE THREAD

**Issue by takazm** [sgjsakura/AspNetCore#35] opened 2019-08-14 08:12 UTC
Tag helpers seem to be broken on asp.net core 3. Stopped working after upgrade

**Comment by sgjsakura** [comment] 2019-08-14 08:13
Hi, thanks for your help, and could you show a more detailed code snippet to demostrate your problem?

Thanks and best wishs,

**Comment by takazm** [comment] 2019-08-14 08:21
Sure. Here is part of my Startup


using Sakura.AspNetCore;
using Sakura.AspNetCore.Mvc; 
using Microsoft.AspNetCore.Authorization; 
using System.Globalization;
 
 public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }
public void ConfigureServices(IServiceCollection services)
        {
            services.AddOptions();
            services.Configure<ApiConfig>(o =>
            {
                o.Url = Configuration["PortalApiUrl"];
                o.Key = Configuration["PortalApiKey"];
                o.Secret = Configuration["PortalApiSecret"];
            });
            services.Configure<SSOApiOptions>(o =>
            {
                o.BaseUri = Configuration["SsoApiUrl"];
                o.ApiKey = Configuration["SsoApiKey"];
                o.ApiSecret = Configuration["SsoApiSecret"];
            });

            services.AddAutoMapper();
            services.AddBootstrapPagerGenerator(O => O.ConfigureDefault());
            services.AddJsReport(new LocalReporting()
                   .UseBinary(JsReportBinary.GetBinary())
                   .AsUtility()
                   .Create());
            services.AddSession();


        }
    }

here is the _viewimports with tags imports

@using WMS;
@using WMS.ViewModels;
@addTagHelper *, WMS
@addTagHelper *, Sakura.AspNetCore.Mvc.PagedList
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers



here is the view declaration

@using Sakura.AspNetCore;
@model IPagedList<WMS.Data.Entities.Inbound.PutAwayRequest>

here is part of the output in browser

<td>
--
  | <div class="btn-group nowrap">
  | <button type="button" class="btn btn-default btn-fill btn-sm">Action</button>
  | <button type="button" class="btn btn-default btn-fill btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  | <span class="caret"></span>
  | <span class="sr-only">Toggle Dropdown</span>
  | </button>
  | <ul class="dropdown-menu">
  | <li style="border-bottom:1px solid #000">
  | <a href="/inbound/receiving/items/0c15958f-acd3-4f89-afc2-89833b2f9040"><i class="fa fa-list"></i>&nbsp;Line Items</a>
  | </li>
  |  
  | <li>
  | <a href="/inbound/receiving/show/0c15958f-acd3-4f89-afc2-89833b2f9040"><i class="fa fa-eye"></i>&nbsp;View Details</a>
  | </li>
  | <li>
  | <a href="/inbound/receiving/edit/0c15958f-acd3-4f89-afc2-89833b2f9040"><i class="fa fa-edit"></i>&nbsp;Edit Details</a>
  | </li>
  | <li style="border-bottom:1px solid #000">
  | <a href="/inbound/receiving/delete/0c15958f-acd3-4f89-afc2-89833b2f9040"><i class="fa fa-trash danger"></i>&nbsp;Delete</a>
  | </li>
  |  
  | <li>
  | <a href="/inbound/receiving/confirm/0c15958f-acd3-4f89-afc2-89833b2f9040"><i class="fa fa-check-circle"></i>&nbsp;Confirm </a>
  | </li>
  | <li>
  | <a target="_blank" href="/inbound/receiving/print/0c15958f-acd3-4f89-afc2-89833b2f9040"><i class="fa fa-print"></i>&nbsp;Print Blind Confirmation</a>
  | </li>
  |  
  | <li>
  | <a href="/inbound/receiving/documents/0c15958f-acd3-4f89-afc2-89833b2f9040"><i class="fa fa-file-archive-o"></i>&nbsp;Supporting Documents</a>
  | </li>
  | </ul>
  | </div>
  | </td>
  | </tr>
  | </tbody>
  | </table>
  | <pager />
  |  
  |  
  | </div>
  | </div>
  | </div>
  | </div>

**Comment by takazm** [comment] 2019-08-14 08:22
`

</tbody>
--
  | </table>
  | <pager />
  |  
  |  
  | </div>

`

**Comment by takazm** [comment] 2019-08-14 08:23
<pager/>

**Comment by sgjsakura** [comment] 2019-09-09 08:32
Hi, thank you for your detailed feedback, since .NET Core 3 is nearly to be published, I'm planed to make a full compatiblity test on .NET Core 3 RTM version. Please be patient for days.

Best wishes,

**Comment by Moosapoor** [comment] 2019-10-15 06:32
Hi,
Are you doing something with this. I've upgraded my .net core to 3 and the pager is gone!
Thanks

**Comment by sgjsakura** [comment] 2019-10-15 11:22
@takazm @Moosapoor The problem is caused since in ASP.NET Core 3.0, package references are replaced by framework references, thus the package dependency was broken and all code cannot work properly.

This problem is fixed in the just published new version, and I'm closing this issue. Please feel free to reopen it if you meet any new problem.

Best regards,

**Closed by sgjsakura** 2019-10-15 11:22 UTC

**Comment by SalehGladius** [comment] 2019-10-23 06:32
After migrating to ASP.NET Core 3.0, This error is displayed:

![image](https://user-images.githubusercontent.com/8124646/67364179-4a25f300-f584-11e9-9891-db6d618c1494.png)

**Comment by sgjsakura** [comment] 2019-10-23 08:09
@SalehGladius Hi, this problem is caused during the updating of the project structure and the `source` attribute is broken. It is now fixed in the lastest version.
